"""Constants for the Waveshare UPS integration."""

from homeassistant.const import Platform

DOMAIN = "waveshare_ups"
PLATFORMS = (Platform.BINARY_SENSOR, Platform.BUTTON, Platform.SENSOR)

CONF_BATTERY_CAPACITY = "battery_capacity"
CONF_BATTERY_CURRENT_THRESHOLD = "battery_current_threshold"
CONF_BATTERY_REPLACEMENT_DATE = "battery_replacement_date"
CONF_AUTOMATIC_TESTING = "automatic_testing"
CONF_BATTERY_REPLACEMENT_DAYS = "battery_replacement_days"
CONF_CYCLE_LIMIT = "cycle_limit"
CONF_CRITICAL_BATTERY_LEVEL = "critical_battery_level"
CONF_DEEP_DISCHARGE_COUNT_LIMIT = "deep_discharge_count_limit"
CONF_DEEP_DISCHARGE_LEVEL = "deep_discharge_level"
CONF_FULL_CHARGE_VOLTAGE = "full_charge_voltage"
CONF_HAT_ADDRESS = "hat_address"
CONF_HAT_BUS = "hat_bus"
CONF_HAT_TYPE = "hat_type"
CONF_HIGH_VOLTAGE_HOURS_LIMIT = "high_voltage_hours_limit"
CONF_HIGH_VOLTAGE_THRESHOLD = "high_voltage_threshold"
CONF_NAME = "name"
CONF_RELAY_ACTIVE_LOW = "relay_active_low"
CONF_RELAY_GPIO = "relay_gpio"
CONF_RELAY_SOURCE_TIMEOUT = "relay_source_timeout"
CONF_RELAY_TEST_TIMEOUT = "relay_test_timeout"
CONF_RUNTIME_DEGRADATION_LEVEL = "runtime_degradation_level"
CONF_RUNTIME_CALIBRATION = "runtime_calibration"
CONF_RUNTIME_LOAD_CURRENT = "runtime_load_current"
CONF_SELF_TEST_DURATION = "self_test_duration"
CONF_SELF_TEST_EMERGENCY_VOLTAGE = "self_test_emergency_voltage"
CONF_SELF_TEST_FAILURE_LEVEL = "self_test_failure_level"
CONF_SELF_TEST_MINIMUM_LEVEL = "self_test_minimum_level"
CONF_SELF_TEST_SETTLING_TIME = "self_test_settling_time"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_WARNING_BATTERY_LEVEL = "warning_battery_level"

DEFAULT_AUTOMATIC_TESTING = False
DEFAULT_BATTERY_CAPACITY = 3200
DEFAULT_BATTERY_CURRENT_THRESHOLD = -100.0
DEFAULT_BATTERY_REPLACEMENT_DAYS = 1095
DEFAULT_CYCLE_LIMIT = 300
DEFAULT_CRITICAL_BATTERY_LEVEL = 10
DEFAULT_DEEP_DISCHARGE_COUNT_LIMIT = 20
DEFAULT_DEEP_DISCHARGE_LEVEL = 20
DEFAULT_FULL_CHARGE_VOLTAGE = 12.49
DEFAULT_HAT_TYPE = "3s"
DEFAULT_HIGH_VOLTAGE_HOURS_LIMIT = 17520
DEFAULT_HIGH_VOLTAGE_THRESHOLD = 12.5
DEFAULT_RELAY_ACTIVE_LOW = False
DEFAULT_RELAY_GPIO = 17
DEFAULT_RELAY_SOURCE_TIMEOUT = 60
DEFAULT_RELAY_TEST_TIMEOUT = 12
DEFAULT_RUNTIME_DEGRADATION_LEVEL = 70
DEFAULT_RUNTIME_CALIBRATION = 100
DEFAULT_RUNTIME_LOAD_CURRENT = 1000
DEFAULT_SELF_TEST_DURATION = 60
DEFAULT_SELF_TEST_EMERGENCY_VOLTAGE = 9.6
DEFAULT_SELF_TEST_FAILURE_LEVEL = 50
DEFAULT_SELF_TEST_MINIMUM_LEVEL = 80
DEFAULT_SELF_TEST_SETTLING_TIME = 15
DEFAULT_UPDATE_INTERVAL = 10
DEFAULT_WARNING_BATTERY_LEVEL = 25

SUPPORTED_MODELS = ("a", "b", "d", "3s")
