"""Configuration defaults and reset handling for the Waveshare UPS."""

from typing import Any

from .const import (
    CONF_AUTOMATIC_TESTING,
    CONF_BATTERY_CAPACITY,
    CONF_BATTERY_CURRENT_THRESHOLD,
    CONF_BATTERY_REPLACEMENT_DATE,
    CONF_BATTERY_REPLACEMENT_DAYS,
    CONF_CYCLE_LIMIT,
    CONF_CRITICAL_BATTERY_LEVEL,
    CONF_DEEP_DISCHARGE_COUNT_LIMIT,
    CONF_DEEP_DISCHARGE_LEVEL,
    CONF_FULL_CHARGE_VOLTAGE,
    CONF_HAT_ADDRESS,
    CONF_HAT_BUS,
    CONF_HAT_TYPE,
    CONF_HIGH_VOLTAGE_HOURS_LIMIT,
    CONF_HIGH_VOLTAGE_THRESHOLD,
    CONF_RELAY_ACTIVE_LOW,
    CONF_RELAY_GPIO,
    CONF_RELAY_SOURCE_TIMEOUT,
    CONF_RELAY_TEST_TIMEOUT,
    CONF_RUNTIME_CALIBRATION,
    CONF_RUNTIME_DEGRADATION_LEVEL,
    CONF_RUNTIME_LOAD_CURRENT,
    CONF_SELF_TEST_DURATION,
    CONF_SELF_TEST_EMERGENCY_VOLTAGE,
    CONF_SELF_TEST_FAILURE_LEVEL,
    CONF_SELF_TEST_MINIMUM_LEVEL,
    CONF_SELF_TEST_SETTLING_TIME,
    CONF_UPDATE_INTERVAL,
    CONF_WARNING_BATTERY_LEVEL,
    DEFAULT_AUTOMATIC_TESTING,
    DEFAULT_BATTERY_CAPACITY,
    DEFAULT_BATTERY_CURRENT_THRESHOLD,
    DEFAULT_BATTERY_REPLACEMENT_DAYS,
    DEFAULT_CYCLE_LIMIT,
    DEFAULT_CRITICAL_BATTERY_LEVEL,
    DEFAULT_DEEP_DISCHARGE_COUNT_LIMIT,
    DEFAULT_DEEP_DISCHARGE_LEVEL,
    DEFAULT_FULL_CHARGE_VOLTAGE,
    DEFAULT_HAT_TYPE,
    DEFAULT_HIGH_VOLTAGE_HOURS_LIMIT,
    DEFAULT_HIGH_VOLTAGE_THRESHOLD,
    DEFAULT_RELAY_ACTIVE_LOW,
    DEFAULT_RELAY_GPIO,
    DEFAULT_RELAY_SOURCE_TIMEOUT,
    DEFAULT_RELAY_TEST_TIMEOUT,
    DEFAULT_RUNTIME_DEGRADATION_LEVEL,
    DEFAULT_RUNTIME_LOAD_CURRENT,
    DEFAULT_SELF_TEST_DURATION,
    DEFAULT_SELF_TEST_EMERGENCY_VOLTAGE,
    DEFAULT_SELF_TEST_FAILURE_LEVEL,
    DEFAULT_SELF_TEST_MINIMUM_LEVEL,
    DEFAULT_SELF_TEST_SETTLING_TIME,
    DEFAULT_UPDATE_INTERVAL,
    DEFAULT_WARNING_BATTERY_LEVEL,
)

INSTALL_DEFAULTS = {
    CONF_AUTOMATIC_TESTING: DEFAULT_AUTOMATIC_TESTING,
    CONF_BATTERY_CAPACITY: DEFAULT_BATTERY_CAPACITY,
    CONF_BATTERY_CURRENT_THRESHOLD: DEFAULT_BATTERY_CURRENT_THRESHOLD,
    CONF_BATTERY_REPLACEMENT_DAYS: DEFAULT_BATTERY_REPLACEMENT_DAYS,
    CONF_CYCLE_LIMIT: DEFAULT_CYCLE_LIMIT,
    CONF_CRITICAL_BATTERY_LEVEL: DEFAULT_CRITICAL_BATTERY_LEVEL,
    CONF_DEEP_DISCHARGE_COUNT_LIMIT: DEFAULT_DEEP_DISCHARGE_COUNT_LIMIT,
    CONF_DEEP_DISCHARGE_LEVEL: DEFAULT_DEEP_DISCHARGE_LEVEL,
    CONF_FULL_CHARGE_VOLTAGE: DEFAULT_FULL_CHARGE_VOLTAGE,
    CONF_HAT_TYPE: DEFAULT_HAT_TYPE,
    CONF_HIGH_VOLTAGE_HOURS_LIMIT: DEFAULT_HIGH_VOLTAGE_HOURS_LIMIT,
    CONF_HIGH_VOLTAGE_THRESHOLD: DEFAULT_HIGH_VOLTAGE_THRESHOLD,
    CONF_RELAY_ACTIVE_LOW: DEFAULT_RELAY_ACTIVE_LOW,
    CONF_RELAY_GPIO: DEFAULT_RELAY_GPIO,
    CONF_RELAY_SOURCE_TIMEOUT: DEFAULT_RELAY_SOURCE_TIMEOUT,
    CONF_RELAY_TEST_TIMEOUT: DEFAULT_RELAY_TEST_TIMEOUT,
    CONF_RUNTIME_DEGRADATION_LEVEL: DEFAULT_RUNTIME_DEGRADATION_LEVEL,
    CONF_RUNTIME_LOAD_CURRENT: DEFAULT_RUNTIME_LOAD_CURRENT,
    CONF_SELF_TEST_DURATION: DEFAULT_SELF_TEST_DURATION,
    CONF_SELF_TEST_EMERGENCY_VOLTAGE: DEFAULT_SELF_TEST_EMERGENCY_VOLTAGE,
    CONF_SELF_TEST_FAILURE_LEVEL: DEFAULT_SELF_TEST_FAILURE_LEVEL,
    CONF_SELF_TEST_MINIMUM_LEVEL: DEFAULT_SELF_TEST_MINIMUM_LEVEL,
    CONF_SELF_TEST_SETTLING_TIME: DEFAULT_SELF_TEST_SETTLING_TIME,
    CONF_UPDATE_INTERVAL: DEFAULT_UPDATE_INTERVAL,
    CONF_WARNING_BATTERY_LEVEL: DEFAULT_WARNING_BATTERY_LEVEL,
}
RESET_PRESERVED_FIELDS = {
    CONF_BATTERY_REPLACEMENT_DATE,
    CONF_HAT_ADDRESS,
    CONF_HAT_BUS,
    CONF_RUNTIME_CALIBRATION,
}


def reset_options(values: dict[str, Any]) -> dict[str, Any]:
    """Return installation defaults while preserving identity and history."""
    reset = dict(INSTALL_DEFAULTS)
    for key in RESET_PRESERVED_FIELDS:
        if key in values:
            reset[key] = values[key]
    return reset
